---
title: "Nittany Amateur Radio Club (NARC) clubhouse guide"
author: "Rick Gilmore (K3ROG)"
date: "`r Sys.time()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
    self_contained: false
---

# Arrival

- Unlock the gate. Use the small key to unlock the padlock. The larger key opens the clubhouse itself. Take the padlock with you to the shack.
- Close the gate and replace the lock bar, but do not re-lock the gate.

ADD PHOTO

- Park anywhere near the shack and off the maintenance road.
- Unlock door of the shack using the larger of the two keys. There is one lock above the door handle. Turn the key to the left (counterclockwise) to unlock the door.
- There are light switches on the left just inside the door.
- Put the padlock and locking bar on the desk near the door.
- Turn up the heat, if needed. To do this, you will need to go to the breaker box near the southeast corner of the shack. By default, we leave breakers 7-14 -- the baseboard and north wall 240 V heaters -- **off**, and the remainder on. So, you will want to these breakers on by pushing the breaker lever to the left to align with the others as seen in the photo.
- The porta potty key is on the desktop to the right of the door.

ADD PHOTO

# Equipment setup

## IC-7610 (yellow tags/labels) called NARC 1

- The IC-7610 is located closest to the door.
- Connect the equipment to the power mains.
    - Plug the large 240 V cable for the amplifier into the 240 V wall outlet.
    - Plug the smaller 120 V cable for the Uninterrupted Power Supply (UPS) into the wall outlet.
- Power up the UPS by pushing the front button.
    - If needed, power up the PC.
- Power up the Astron RS-35A power supply that powers the IC-7610.
- Before you power up the radio, connect it to a suitable antenna.
    - The antenna connections are located on the north wall.
    - Plug the cable from the radio (yellow tag) into the cable connector for one of the antennas, for example, one of the triband Yagi's for 10 - 20 m.
- Power up the IC-7610 by pressing and briefly holding the power button.
- The IC-7610 is connected to the Elecraft KPA1500 amplifier. The power supply for the KPA1500 is under the desk on a small footstool.
- Power up the KPA1500 by pressing the on switch on the lower right hand side of the KPA1500.

### Operating the IC-7610

### Accessories

- The default configuration uses the ICOM SM-50 desk mic.
- There is a Clipper footswitch for the PTT on the floor.
- There is a Heil headset.
- We have a Nifty Mini-manual and other manuals are located in the drawer under the radio.

## Elecraft K3S (<span class="red">red tag) NARC 2 station

- Connect the UPS to the wall power outlet.
- Connect the 240 V Elecraft KPA1500 power supply cable to the 240 V supply.
- Power up the Astron RS-35A power supply by pressing the red 'on' switch on the lower left front part of the panel.
- Power up the K3S.
- Power up the KPA1500 by pressing the 'On' switch on the lower right panel.

### Accessories

- There is an Elecraft P3 panadapter connected to the K3S.
- There is a footswitch on the floor.
- There is a Heil Pro 7 headset.
- There is a Bencher BY-1 paddle.

# Departure

- Power down all the equipment you used.
- Turn off the UPS and unplug it from the wall sockets.
- Unplug the power amplifier power supplies from the wall sockets.
- Unplug the antenna rotator power supplies from the wall sockets.
- Turn breakers 7-14 -- the baseboard and north wall 240 V heaters -- **off**.
- Return the porta potty key to the desktop to the right side of the door.
- Take the padlock to gate with you.
- As you leave the shack, close and lock the door by turning the key to the right (clockwise). Check again to confirm that the door is closed and locked.
- As you reach the gate, stop, remove the lock bar, and swing the gate out of the way.
- Drive through and stop just outside the gate.
- Swing the gate back into closed position. Place the lock bar in position, and lock the gate.
- Please text Rick (814-777-3298) or Eric (814-867-3393) when you leave. We ask that you report any issues that need to be addressed.
